### ISSUE TITLE
Slice Concatenate Needs Attention

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/Genesis-1.3-Version2#12]
Running genesis2-mpi with a large number of slices `>=4000` causes a huge delay after simulation due to concatenation of output.

Steps to Reproduce
--------------------
- Use genesis2-mpi with openmpi
- Invoke genesis2 to create template.in
- Modify template.in and set `itdp = 1` and `nslice = 4129`
- Execute with: `mpirun genesis2-mpi template.in`
- Notice the delay at end

**Comment by ChristopherMayes** [comment]
There is a patch for that: https://github.com/slaclab/lume-genesis/blob/master/extra/fast_cat/mpi.f

We should test that the output is the same.

**Comment by ChristopherMayes** [comment]
There is an issue with this: Genesis normally skips the tail slices when concatenating the file. Some of the early slices are also skipped for some reason. This method concatenates them all, but then there are missing ones in the tail (low slice ix).

**Comment by ChristopherMayes** [comment]
With `iotail=1`, results are practically identical.
